baseURL = "https://therealhan.com/"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
title = "欢迎光临寒舍"
theme = "stack"

[params]
    mainSections = ["posts"]
    featuredImageField = "image"
    rssFullContent = true
    lazyImage = true
    defaultTheme = "dark"
    # customCSS = ["scss/custom.scss"]

[params.colorScheme]
  toggle = true

[params.dateFormat]
  published = "2006/01/02"
  lastUpdated = "2006/01/02"

[params.math]
  enable = true
  use = "katex"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  noClasses = false
  style = "github-dark"

[params.sidebar.avatar]
  enabled = true
  local = true
  src = "img/avatar.jpg"

[markup.tableOfContents]
  startLevel = 2
  endLevel = 4

[params.article]
  readingTime = true
  wordCount = true
  showSummary = true

[[params.widgets.page]]
  type = "toc"

[[params.widgets.page]]
  type = "random-illustration"

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$']]
    inline = [['\(', '\)']]

[markup.goldmark.extensions.extras.mark]
  enable = true

[[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/kobespecial/therealhan-blog"
  [menu.social.params]
    icon = "brand-github"

[[menu.main]]
  name = "主页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 3

[[menu.main]]
  name = "碎碎念"
  url = "/blogs/"
  weight = 4

[outputs]
  home = ["HTML", "RSS"]
